<?php
// $Id: fhcivimail.module,v 0.1 2007/10/11 14:18:34 ema Exp $


$mod_path = drupal_get_path('module', 'fhcivimail');
require_once $mod_path . "/libgmailer.php";

/**
 * Implementation of hook_settings
 *
 */
function fhcivimail_settings(){

  $form['fhcivimail_verp'] = array(
    '#type' => 'textfield',
    '#title' => t('verp'),
    '#default_value' => variable_get('fhcivimail_verp', '-'), 
  );

  $form['fhcivimail_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('GMail domain'),
    '#default_value' => variable_get('fhcivimail_domain', 'fighthunger.org'), 
  );
  
  // Bounces
  $form['fhcivimail_bounce_group'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Bounce mailbox options'),
    '#collapsible' => TRUE,
    '#collapsed'   => FALSE,
  );  
  $form['fhcivimail_bounce_group']['fhcivimail_bounce_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('fhcivimail_bounce_user', ''), 
  );
  $form['fhcivimail_bounce_group']['fhcivimail_bounce_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('fhcivimail_bounce_password', ''), 
  );
  $form['fhcivimail_bounce_group']['fhcivimail_bounce_status'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#default_value' => variable_get('fhcivimail_bounce_status',false),
    '#options' => array(false => t('Inactive'), true => t('Active')),
  );

  // Unsubscriptions
  $form['fhcivimail_unsubscribe_group'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Unsubscribe mailbox options'),
    '#collapsible' => TRUE,
    '#collapsed'   => FALSE,
  );  
  $form['fhcivimail_unsubscribe_group']['fhcivimail_unsubscribe_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('fhcivimail_unsubscribe_user', ''), 
  );
  $form['fhcivimail_unsubscribe_group']['fhcivimail_unsubscribe_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('fhcivimail_unsubscribe_password', ''), 
  );
  $form['fhcivimail_unsubscribe_group']['fhcivimail_unsubscribe_status'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#default_value' => variable_get('fhcivimail_unsubscribe_status',false),
    '#options' => array(false => t('Inactive'), true => t('Active')),
  );

  // Optout
  $form['fhcivimail_optout_group'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Optout mailbox options'),
    '#collapsible' => TRUE,
    '#collapsed'   => FALSE,
  );  
  $form['fhcivimail_optout_group']['fhcivimail_optout_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => variable_get('fhcivimail_optout_user', ''), 
  );
  $form['fhcivimail_optout_group']['fhcivimail_optout_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('fhcivimail_optout_password', ''), 
  );
  $form['fhcivimail_optout_group']['fhcivimail_optout_status'] = array(
    '#type' => 'select',
    '#title' => t('Status'),
    '#default_value' => variable_get('fhcivimail_optout_status',false),
    '#options' => array(false => t('Inactive'), true => t('Active')),
  );

  return $form;
}

function fhcivimail_cron() {
  if(variable_get('fhcivimail_optout_status',false)) {
    watchdog('fhcivimail', 'Check optouts');
    $result = _fhcivimail_check_mail_box('optout');
    if($result>0) watchdog('fhcivimail', "optouts processed: $result");  
  }
  if(variable_get('fhcivimail_unsubscribe_status',false)) {
    watchdog('fhcivimail', 'Check unsubscriptions');
    $result = _fhcivimail_check_mail_box('unsubscribe');
    if($result>0) watchdog('fhcivimail', "Unsubriptions processed: $result");  
  }
  if(variable_get('fhcivimail_bounce_status',false)) {
    watchdog('fhcivimail', 'Check bounces');
    $result = _fhcivimail_check_mail_box('bounce');
    if($result>0) watchdog('fhcivimail', "Bounces processed: $result");  
  }
}

/**
 * Implementation of hook_menu
 *
 *
 */
function fhcivimail_menu($may_cache){
  $items = array();
  if ($may_cache) {

    $items[] = array(
      'path'     => 'admin/fhcivimail',
      'title'    => t('CiviMail helpers'), 
      'callback' => 'fhcivimail_helpers',
      'access'   => user_access('administer CiviCRM')
    );
    $items[] = array(
      'path'     => 'admin/fhcivimail/helpers',
      'title'    => t('CiviMail helpers'), 
      'callback' => 'fhcivimail_helpers',
      'type'     => MENU_DEFAULT_LOCAL_TASK,
      'access'   => user_access('administer CiviCRM'),
      'weight'   => -99
    );

    $items[] = array(
      'path' => 'admin/fhcivimail/bounce',
      'title' => t('CiviMail bounces'), 
      'callback' => 'fhcivimail_bounces',
      'type' => MENU_LOCAL_TASK,
      'access' => user_access('administer CiviCRM')
    );
    $items[] = array(
      'path' => 'admin/fhcivimail/optout',
      'title' => t('CiviMail optouts'), 
      'callback' => 'fhcivimail_optout',
      'type' => MENU_LOCAL_TASK,
      'access' => user_access('administer CiviCRM')
    );
    $items[] = array(
      'path' => 'admin/fhcivimail/unsubscribe',
      'title' => t('CiviMail unsubscriptions'), 
      'callback' => 'fhcivimail_unsubscribe',
      'type' => MENU_LOCAL_TASK,
      'access' => user_access('administer CiviCRM')
    );
  }      
  return $items;
}

function fhcivimail_access($op, $node) {
  global $user;
  //Administrator can see all contacts
  if (user_access('administer CiviCRM'))
    return TRUE;

  //We must explicitly return to deny access
  return FALSE;
}

function fhcivimail_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      // This description is shown in the listing at admin/modules.
      return t('<b>FH:</b> A module that helps CiviMail. <b>Require CiviCRM</b>');
  }
} 


/**
 * fhCiviMail: CiviNail helpers
 */

/**
 * Initialization checks
 */
function fhcivimail_check_init() {
  if (function_exists('civicrm_initialize')) {
    civicrm_initialize(TRUE);
    $mod_path = drupal_get_path('module', 'civicrm');
    require_once $mod_path . "/../api/Mailer.php";
    return TRUE;
  }
  return FALSE;
}

function _fhcivimail_extract_data($recv_email) {
  $data = array();
  list($to, $data['domain']) = split("@",  $recv_email );
  list($data1, $data2)  = split( variable_get('fhcivimail_verp', '-'),  $to );
  list($data['dest'], $data['domain_id'], $data['job'], $data['queue'], $data['hash']) = split("\.", $data1);
  if($data2) $data['bounce_address'] = str_replace("=", "@", $data2);
  return $data;
}

function _fhcivimail_crm_action($action, $mail) {

  $data = _fhcivimail_extract_data($mail['recv_email'][0]);
  
  if( fhcivimail_check_init() && ($data['dest']===$action) ) {
    switch ($data['dest']) {
      case 'bounce':
        $result = crm_mailer_event_bounce($data['job'], $data['queue'], $data['hash'], $mail['body']);
        break;
      case 'optout':
        $result = crm_mailer_event_domain_unsubscribe($data['job'], $data['queue'], $data['hash']);
        break;
      case 'unsubscribe':
        $result = crm_mailer_event_unsubscribe($data['job'], $data['queue'], $data['hash']);
        break;
    }
    watchdog('fhcivimal', "<b>" . $mail['sender_email'] . "</b>: (" . implode(', ', $data) . "): $result");
  } else {
    $result = false;
  }
  return $result;
}

function _fhcivimail_get_box($gmailer, $action) {
  $gmail_acc = variable_get('fhcivimail_' . $action . '_user', '');
  $gmail_pwd = variable_get('fhcivimail_' . $action . '_password', ''); 
  $gmail_domain = variable_get('fhcivimail_domain', 'fighthunger.org'); 
  $my_timezone = '+1';
  
  if ($gmailer->created) {
  
// connect to gmail account
    $gmailer->setDomain($gmail_domain);
    $gmailer->setLoginInfo($gmail_acc, $gmail_pwd, $my_timezone);
    if ($gmailer->connect()) {
      $count = 0;

// fetch mailbox
      $gmailer->fetchBox(GM_LABEL, $action, 0);
      $snapshot = $gmailer->getSnapshot(GM_STANDARD);
      $result = $snapshot->box;
    } else {
      watchdog('fhcivimail', "Fail to connect because: ".$gmailer->lastActionStatus());
      $result = NULL;
    }
  } else {
    watchdog('fhcivimail', "Failed to create GMailer because: ".$gmailer->lastActionStatus());
    $result = NULL;
  }
  return $result;
}

function _fhcivimail_check_mail_box($action) {

  $gmail_acc = variable_get('fhcivimail_' . $action . '_user', '');
  $gmail_pwd = variable_get('fhcivimail_' . $action . '_password', ''); 
  $gmail_domain = variable_get('fhcivimail_domain', 'fighthunger.org'); 
  $my_timezone = '+1';
  $count = false;
  
  $gmailer = new GMailer();
  if ($gmailer->created) {
  
// connect to gmail account
    $gmailer->setDomain($gmail_domain);
    $gmailer->setLoginInfo($gmail_acc, $gmail_pwd, $my_timezone);
    if ($gmailer->connect()) {
      $count = 0;

// fetch mailbox
      $gmailer->fetchBox(GM_LABEL, $action, 0);
      $snapshot = $gmailer->getSnapshot(GM_STANDARD);
      $box = $snapshot->box;

// fetch mail
      foreach($box as $conv) {
        $message_id = $conv['id'];
        $data = array();        
        $gmailer->fetchBox(GM_CONVERSATION, $message_id, 0);
        $snapshot = $gmailer->getSnapshot(GM_CONVERSATION);
        $mail = $snapshot->conv[0];

// process mail 
        if(_fhcivimail_crm_action($action, $mail)) {
          $gmailer->performAction(GM_ACT_APPLYLABEL,  $message_id, $action . "_done");
          $gmailer->performAction(GM_ACT_REMOVELABEL, $message_id, "$action");
          $gmailer->performAction(GM_ACT_ARCHIVE,     $message_id);
          $count++;
        } else {
          $gmailer->performAction(GM_ACT_STAR,  $message_id);
        }
      } 
    } else {
      watchdog('fhcivimail', "Fail to connect because: ".$gmailer->lastActionStatus());
    }
  } else {
    watchdog('fhcivimail', "Failed to create GMailer because: ".$gmailer->lastActionStatus());
  }
  return $count;
}


function fhcivimail_helpers() {
  return 'pippo';
}

function fhcivimail_bounces() {

  // set header
  $header = array(
    array('data' => t('email')  ),
    array('data' => t('dest')   ),
    array('data' => t('domain') ),
    array('data' => t('job')    ),
    array('data' => t('queue')  ),
    array('data' => t('hash')   ),
  );

  // get bounces
  $gmailer = new GMailer();
  $box = _fhcivimail_get_box($gmailer, 'bounce');

// fetch mail
  foreach($box as $conv) {
    $message_id = $conv['id'];
    $data = array();    
    $gmailer->fetchBox(GM_CONVERSATION, $message_id, 0);
    $snapshot = $gmailer->getSnapshot(GM_CONVERSATION);
    $mail = $snapshot->conv[0];
    $data = _fhcivimail_extract_data($mail['recv_email'][0]);
    $rows[] = array($mail['sender_email'], $data['dest'], $data['domain_id'], $data['job'], $data['queue'], $data['hash']);
  }
  $output  = theme('table', $header, $rows);
  return $output;
}

function fhcivimail_optout() {
  return 'pippo optout';
}

function fhcivimail_unsubscribe() {
  return 'pippo unsubscribe';
}

?>
