<?php
// $Id: fhcommerce.module $

/**
 * @file
 * Fighthunger common API
 * 
 * Some e-commerce customizations for Fighthuger
 *  
 * Developed by Jose A. Reyero,  http://www.reyero.net
 * for FightHunger.org
 */


/**
 * Implementation of hook_help().
 */
function fhcommerce_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('<strong>FH:</strong> Fighthunger e-commerce customization.');
  }
}

/**
 * Implementation of hook_form_alter().
 */
function fhcommerce_form_alter($form_id, &$form) {
  // Add default address for e-commerce module. Administrator can create addresses for other users
  if ($form_id == 'address' && $form['submit']['#value'] == t('Create new address') && $uid = $form['uid']['#value']) {
  	$account = user_load(array('uid' => $uid));
    // Set personal information
    $form['firstname']['#default_value'] = $account->first_name;
    $form['lastname']['#default_value'] = $account->last_name;
    if ($location = $account->location) {
    	$form['country']['#default_value'] = $location['country'];
      $form['street1']['#default_value'] = $location['street'];
      $form['street2']['#default_value'] = $location['additional'];
      $form['city']['#default_value'] = $location['city'];
      $form['state']['#default_value'] = $location['province'];
      $form['zip']['#default_value'] = $location['postal_code'];
    }
  }
}

?>