<?php
// $Id: location.be.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Belgium

function location_province_list_be() {
  return array('VAN' => "Antwerpen",
    'VBR' => "Vlaams Brabant",
    'VLI' => "Limburg",
    'VOV' => "Oost-Vlaanderen",
    'VWV' => "West-Vlaanderen",
    'WBR' => "Brabant Wallon",
    'WHT' => "Hainaut",
    'WLG' => "Liege",
    'WLX' => "Luxembourg",
    'WNA' => "Namur");
}

?>