<?php
// $Id: location.au.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Australia

function location_province_list_au() {
  return array('ACT' => "Australian Capital Territory",
    'NSW' => "New South Wales",
    'NT' => "Northern Territory",
    'QLD' => "Queensland",
    'SA' => "South Australia",
    'TAS' => "Tasmania",
    'VIC' => "Victoria",
    'WA' => "Western Australia");
}

?>