<?php
// $Id: location.nr.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Nauru

function location_province_list_nr() {
  return array('AO' => "Aiwo",
    'AA' => "Anabar",
    'AT' => "Anetan",
    'AI' => "Anibare",
    'BA' => "Baiti",
    'BO' => "Boe",
    'BU' => "Buada",
    'DE' => "Denigomodu",
    'EW' => "Ewa",
    'IJ' => "Ijuw",
    'ME' => "Meneng",
    'NI' => "Nibok",
    'UA' => "Uaboe",
    'YA' => "Yaren");
}

?>