<?php
// $Id: tax.module,v 1.16.2.4 2006/10/02 00:33:21 gordon Exp $

/********************************************************************
 * Drupal Hooks
 ********************************************************************/

/**
 * Implementation of hook_help()
 */
function tax_help($section = 'admin/help#tax') {
  switch ($section) {
    case 'admin/modules#description':
      return t('<b>EC:</b> Enable a tax API for ecommerce.');
    case 'admin/store/tax':
      return t('Enter tax rules here.');
    case 'admin/settings/tax':
      return t('tax calculation methods are <a href="%tax_calc_url">here</a>.', array('%tax_calc_url' => url('admin/store/tax')));
  }

  return $output;
}

/**
 * Implementation of hook_menu()
 */
function tax_menu($may_cache) {
  $items = array();
  $access = user_access('administer store');
  if ($may_cache) {
    $items[] = array('path' => 'admin/store/tax', 'title' => t('taxes'), 'access' => $access, 'callback'=>'tax_admin_controller');
    $items[] = array('path' => 'admin/store/tax/list', 'title' => t('taxes'), 'access' => $access, 'type' => MENU_DEFAULT_LOCAL_TASK, 'weight' => -10);
    $items[] = array('path' => 'admin/store/tax/add', 'title' => t('add tax'), 'access' => $access, 'type' => MENU_LOCAL_TASK);
    $items[] = array('path' => 'admin/store/tax/edit', 'title' => t('edit tax'), 'access' => $access, 'type' => MENU_CALLBACK);
    $items[] = array('path' => 'admin/store/tax/delete', 'title' => t('delete tax'), 'access' => $access, 'type' => MENU_CALLBACK);
    $items[] = array('path' => 'admin/store/tax/add/autocomplete', 'title' => t('tax autocomplete'), 'callback' => 'tax_autocomplete_state', 'access' => $access, 'type' => MENU_CALLBACK);
  }
  return $items;
}

/**
 * Implementation of hook_checkoutapi().
 */
function tax_checkoutapi(&$txn, $op, $arg3 = NULL, $arg4 = NULL) {
  $output = '';
  switch ($op) {
    case 'review':
      if ($txn == 'tax') return TRUE;
      $box['subject'] = t('Tax');
      $billing = $txn->address['billing'];
      $rules = tax_get_rules();
      $states = store_build_states();
      $total_tax = 0;
      $taxable_amount = 0;

      foreach ($txn->items as $item) {
        if (product_is_shippable($item->vid)) {
          $taxable_amount += store_adjust_misc($txn, $item) * $item->qty;
        }
      }

      foreach ($rules as $rule) {
        switch ($rule->realm) {
          case 'city':
            if ($billing->city == $rule->realm_value && tax_rule_product_match($txn, $rule)) {
              if ($tax = tax_calculate($taxable_amount, $rule->operand, $rule->operator)) {
                $total_tax += $tax;
              }
            }
            break;
          case 'country':
            if ($billing->country == $rule->realm_value && tax_rule_product_match($txn, $rule)) {
              if ($tax = tax_calculate($taxable_amount, $rule->operand, $rule->operator)) {
                $total_tax += $tax;
              }
            }
            break;
          case 'state':
            if ($billing->state) {
              if ($states[$billing->state] == $rule->realm_value && tax_rule_product_match($txn, $rule)) {
                if ($tax = tax_calculate($taxable_amount, $rule->operand, $rule->operator)) {
                  $total_tax += $tax;
                }
              }
            }
            break;
        }
      }
      if ($total_tax) {
        if (($key = store_search_misc(array('type' => 'tax'), $txn)) !== false) {
          $txn->misc[$key]->price = $total_tax;
        }
        else {
          $misc = array(
            'type' => 'tax',
            'description' => 'Tax',
            'price' => $total_tax,
            'weight' => 10
          );
          $txn->misc[] = (object)$misc;
        }
      }

      return;
  }
}

/********************************************************************
 * Module Functions :: Controllers
 ********************************************************************/

/**
 * Controller. This callback is invoked via menu() when "admin/store/tax*" is hit.
 */
function tax_admin_controller($action = '') {
  $edit = $_POST['edit'];
  $op = $_POST["op"];

  switch ($op ? $op : $action) {
    case 'add':
      $output = tax_form_screen1($edit);
      break;

    // Step 2 of adding new tax rule.
    case t('Next'):
      $output = tax_form_screen2($edit);
      break;

    case 'edit':
      $edit = tax_get_rule(arg(4));
      $output = tax_form_screen1($edit);
      $output .= tax_form_screen2($edit);
      $output = $output;
      break;

    case 'delete':
      if (is_numeric(arg(4))) {
        db_query('DELETE FROM {ec_tax} WHERE taxid = %d', arg(4));
        drupal_set_message(t('tax rule deleted'));
        drupal_goto('admin/store/tax');
      }
      break;

    case t('Submit'):
    case t('Update');
      if (tax_admin_form_validate($edit)) {
        tax_save_rule($edit);
        drupal_goto('admin/store/tax');
      }
      else {
        $output = tax_form_screen2($edit);
      }
      break;

    default:
      $output = tax_admin_overview();
  }

  return $output;
}

/**
 * Show an overview of all the tax rules.
 */
function tax_admin_overview() {
  $output = '';
  $header = array(t('rule'), t('operations'));

  $result = db_query('SELECT * FROM {ec_tax}');
  while ($rule = db_fetch_object($result)) {
    $rows[] = array(t("Add %operator%operand where %realm = '%realm-value'", array('%operator' => $rule->operator, '%operand' => ($rule->operand == '+' ? '' : '%'), '%realm' => $rule->realm, '%realm-value' => $rule->realm_value)), l(t('edit'), "admin/store/tax/edit/$rule->taxid"). ' | '. l(t('delete'), "admin/store/tax/delete/$rule->taxid"));
  }

  if (count($rows) == 0) {
    $rows[] = array(array('data' => '<em>'. t('There are currently no tax rules.') .'</em>', 'colspan' => 5));
  }
  $output .= theme('table', $header, $rows);

  return $output;
}

/********************************************************************
 * Module Functions :: Validators
 ********************************************************************/

/**
 * Validate a tax rule.
 */
function tax_admin_form_validate(&$edit) {
  $errors = array();
  if (!$edit['realm_value']) {
    $errors['realm_value'] = t('You must enter a location value.');
  }

  if (empty($edit['ptype'])) {
    $errors['ptype'] = t('You must choose a product type.');
  }

  if (isset($edit['rate'])) {
    if (strstr($edit['rate'], '%')) {
      $edit['operand']  = '%';
      $edit['operator'] = rtrim($edit['rate'], '%');
    }
    else {
      $edit['operand']  = '+';
      $edit['operator'] = ltrim($edit['rate'], '+');
    }

    if (!is_numeric($edit['operator'])) {
      $errors['operator'] = t('Invalid operator');
    }
  }
  else {
    $errors['rate'] = t('You must enter a rate.');
  }

  foreach ($errors as $name => $message) {
    form_set_error($name, $message);
  }

  return count($errors) == 0;
}

/********************************************************************
 * Module Functions :: Save Routines
 ********************************************************************/

function tax_save_rule($edit) {
  $fields = tax_fields();
  if ($edit['taxid'] > 0 && db_result(db_query('SELECT COUNT(taxid) FROM {ec_tax} WHERE taxid = %d', $edit['taxid']))) {
    // Prepare the query:
    foreach ($edit as $key => $value) {
      if (in_array($key, $fields)) {
        if ($key == 'ptype') {
          $value = implode(',', $value);
        }
        $q[] = db_escape_string($key) ." = '%s'";
        $v[] = $value;
      }
    }

    db_query("UPDATE {ec_tax} SET ". implode(', ', $q) ." WHERE taxid = ". (int) $edit['taxid'], $v);
  }
  else {
    $edit['taxid'] = db_next_id('{ec_tax}_taxid');
    // Prepare the query:
    foreach ($edit as $key => $value) {
      if (in_array((string) $key, $fields)) {
        if ($key == 'ptype') {
          $value = implode(',', $value);
        }
        $k[] = db_escape_string($key);
        $v[] = $value;
        $s[] = "'%s'";
      }
    }
    
    db_query("INSERT INTO {ec_tax} (". implode(", ", $k) .") VALUES(". implode(", ", $s) .")", $v);
  }
}

function tax_form_screen1($edit = array()) {
  $name = tax_invoke_taxapi($edit, 'name');
  $locations = array(
    'state' => t('State / Province / Region'), 
    'country' => t('Country'), 
    'city' => t('City')
  );
  $form['realm'] = array(
    '#type' => 'select',
    '#title' => t('Type of Location to define the new tax rule for'),
    '#default_value' => $edit['realm'],
    '#options' => $locations,
    '#description' => t('State / Province / Region'),
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Next')
  );
  return drupal_get_form('tax_form_screen1', $form);
}

function tax_form_screen2($edit = array()) {
  $help = t('This value will be checked against the customer\'s shipping address.');
  if ($edit['realm'] == 'state') {
    $form['realm_value'] = array(
      '#type' => 'textfield',
      '#title' => t('Value for State / Province / Region'),
      '#default_value' => $edit['realm_value'],
      '#size' => 32,
      '#maxlength' => 32,
      '#autocomplete_path' => 'admin/store/tax/add/autocomplete',
      '#description' => $help,
    );
  }
  elseif ($edit['realm'] == 'country') {
    $country = store_build_countries();
    array_unshift($country, t('Please choose...'));
    $form['realm_value'] = array(
      '#type' => 'select',
      '#title' => t('Country'),
      '#default_value' => ($edit['realm_value'] ? $edit['realm_value'] : variable_get('ec_country', '')),
      '#options' => $country,
      '#description' => t('Country'),
    );
  }
  elseif ($edit['realm'] == 'city') {
    $form['realm_value'] = array(
      '#type' => 'textfield',
      '#default_value' => $edit['realm_value'], 
      '#maxlength' =>  32, 
      '#description' => t('This value will be checked against the customer\'s shipping address.'), 
    );
  }
  else {
    #$form = tax_invoke_taxapi($edit, 'admin form');
    #$output .= $form[0];
    
    /*
    * The above is not solved yet, don't really know what this call is for?!
    * Should there ever be an else to this structure?
    */
  }
  $form['realm'] = array(
    '#type' => 'hidden', 
    '#value' => $edit['realm']
  );
  $form['rate'] = array(
      '#type' => 'textfield',
      '#title' => t('Adjustment'),
      '#default_value' => $edit['rate'], 
      '#maxlength' =>  13, 
      '#description' => t('This rate can be a simple price addition or a percentage multiplier. For example, to add a 5.00 tax, enter +5.00. To multiply the gross price times 75%, enter 75%. If no operand is given, addition is assumed.'), 
    );
  $ptypes = product_get_ptypes();
  asort($ptypes);
   $form['ptype'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Product type'),
    '#default_value' => $edit['ptype'],
    '#options' => $ptypes,
    '#description' => t('Check the product types this tax rule applies to.'),
  );
  if ($edit['taxid']) {
    $form['taxid'] = array(
      '#type' => 'hidden', 
      '#value' => $edit['taxid']
    );
    $form['submit'] = array(
      '#type' => 'submit', 
      '#value' => t('Update')
    );
  }
  else {
    $form['submit'] = array(
      '#type' => 'submit', 
      '#value' => t('Submit')
    );
  }
  return drupal_get_form('tax_form_screen2', $form);
}

/**
 * Retrieve a pipe delimited string of autocomplete suggestions for existing locations
 */
function tax_autocomplete_state($string) {
  $states = store_build_states();
  $matches = array();
  foreach ($states as $state) {
    if (preg_match("/^$string(.+?)/i", $state)) {
      $matches[$state] = $state;
    }
  }
  print drupal_implode_autocomplete($matches);
  exit();
}

/**
 * Invoke a hook_nodeapi() operation in all modules.
 *
 * @param &$txn
 *   A txn object.
 * @param $op
 *   A string containing the name of the taxapi operation.
 * @param $a3, $a4
 *   Arguments to pass on to the hook, after the $txn and $op arguments.
 * @return
 *   The returned value of the invoked hooks.
 */
function tax_invoke_taxapi(&$txn, $op, $a3 = NULL, $a4 = NULL) {
  $return = array();
  foreach (module_list() as $name) {
    $function = $name .'_taxapi';
    if (function_exists($function)) {
      $result = $function($txn, $op, $a3, $a4);
      if (is_array($result)) {
        $return = array_merge($return, $result);
      }
      else if (isset($result)) {
        $return[] = $result;
      }
    }
  }
  return $return;
}

/**
 * Get tax rule from the DB.
 */
function tax_get_rule($tid) {
  $result = db_query('SELECT * FROM {ec_tax} WHERE taxid = %d', (int) $tid);
  $rule = db_fetch_array($result);
  $rule['rate'] = $rule['operand'] == '%' ? $rule['operator'] . $rule['operand'] : $rule['operand'] . $rule['operator'];
  $rule['ptype'] = explode(',', $rule['ptype']);
  return $rule;
}

/**
 * Get all rules from the DB.
 */
function tax_get_rules() {
  $rules = array();
  $result = db_query('SELECT * FROM {ec_tax}');
  while ($rule = db_fetch_object($result)) {
    $rules[] = $rule;
  }
  return $rules;
}

/**
 * Return the tax cost for a given rule.
 */
function tax_calculate($gross, $operand, $op2) {
  switch ($operand) {
    case '+':
      return $op2;
    case '%':
      return($gross * ($op2/100));
  }
}

/**
 * Return TRUE if $rule applies to the current products in the cart.
 */
function tax_rule_product_match($txn, $rule) {
  $ptypes = explode(',', $rule->ptype);
  foreach ($txn->items as $item) {
    if (in_array($item->ptype, $ptypes)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Returnt the table names in the database.
 */
function tax_fields() {
  return array('taxid', 'realm', 'realm_value', 'ptype', 'operator', 'operand');
}
