<?php /* Smarty version 2.6.12-dev, created on 2006-04-20 08:49:17
         compiled from CRM/common/feedback.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'ts', 'CRM/common/feedback.tpl', 2, false),)), $this); ?>
<div class="messages status" id="feedback-request"> 
<p><?php $this->_tag_stack[] = array('ts', array('1' => '1.3')); smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat=true);while ($_block_repeat) { ob_start(); ?>This site is running CiviCRM v%1.<?php $_block_content = ob_get_contents(); ob_end_clean(); echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat=false); }  array_pop($this->_tag_stack); ?></p>
<p><?php $this->_tag_stack[] = array('ts', array('1' => 'http://objectledge.org/jira/browse/CRM?report=com.atlassian.jira.plugin.system.project:roadmap-panel')); smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat=true);while ($_block_repeat) { ob_start(); ?>To see a list of known bugs and issues, and to report new bugs, please use our <a href="%1" target="_blank">bug-tracking system</a>.<?php $_block_content = ob_get_contents(); ob_end_clean(); echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat=false); }  array_pop($this->_tag_stack); ?></p>
<p><?php $this->_tag_stack[] = array('ts', array('1' => 'http://objectledge.org/confluence/display/CRM/Demo')); smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat=true);while ($_block_repeat) { ob_start(); ?>Please add any comments on the look and feel of these pages, along with workflow issues, on the <a href="%1">CiviCRM Comments Page</a>.<?php $_block_content = ob_get_contents(); ob_end_clean(); echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat=false); }  array_pop($this->_tag_stack); ?></p>
<small>
<p><?php $this->_tag_stack[] = array('ts', array('1' => 'http://www.affero.org/oagpl.html','2' => 'http://downloads.openngo.org/civicrm/')); smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat=true);while ($_block_repeat) { ob_start(); ?>CiviCRM software is openly available to any person or organization under the terms of the <a href="%1">Affero General Public License (AGPL)</a>. Source code can be downloaded from our <a href="%2">downloads site</a>.<?php $_block_content = ob_get_contents(); ob_end_clean(); echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat=false); }  array_pop($this->_tag_stack); ?></p>
</small>
</div> 