<?php
// $Id: location.lc.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Saint Lucia

function location_province_list_lc() {
  return array('AR' => "Anse-la-Raye",
    'CA' => "Castries",
    'CH' => "Choiseul",
    'DA' => "Dauphin",
    'DE' => "Dennery",
    'GI' => "Gros-Islet",
    'LA' => "Laborie",
    'MI' => "Micoud",
    'PR' => "Praslin",
    'SO' => "Soufriere",
    'VF' => "Vieux-Fort");
}

?>