<?php
// $Id: location.sb.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Solomon Islands

function location_province_list_sb() {
  return array('CE' => "Central",
    'CH' => "Choiseul",
    'GC' => "Guadalcanal",
    'HO' => "Honiara",
    'IS' => "Isabel",
    'MK' => "Makira",
    'ML' => "Malaita",
    'RB' => "Rennell and Bellona",
    'TM' => "Temotu",
    'WE' => "Western");
}

?>