<?php
// $Id: fhpage.module,v 1.168 2005-04-26 15:55:01 jose Exp $

/**
 * @file
 * Fighthunger site specific pages
 * 
 * Developed by Jose A. Reyero,  http://www.reyero.net
 * for FightHunger, http://www.fighthunger.org
 * 
 */

/**
 * Implementation of hook_help().
 */
function fhpage_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('<strong>FH:</strong> Produces specific site pages.');
  }
}

/**
 * Implementation of hook_settings().
 */
function fhpage_settings() {
  
  foreach(_fhpage_page_list() as $type => $name) {
  	$default = variable_get("fhpage_type_$type", array());
  	$form["fhpage_type_$type"] = array('#type' => 'fieldset', '#title' => $name, '#tree' => TRUE);
    $form["fhpage_type_$type"]['title'] = array('#type' => 'textfield', '#title' => t('Title'),
      '#default_value' => $default['title'],
    );
    $form["fhpage_type_$type"]['header'] = array('#type' => 'textarea', '#title' => t('Page header'),
      '#default_value' => $default['header'],
    );
    $form["fhpage_type_$type"]['pager'] = array('#type' => 'textfield', '#title' => t('Number of items'),
      '#default_value' => $default['pager'], '#description' => t('Number of items per page. 0 = Show all.')
    );   	
  }
  return $form;
}

/**
 * Implementation of hook_menu().
 */
function fhpage_menu($may_cache){
    $items = array();
  if($may_cache) {
    $items[] = array('path' => 'page', 'callback' => 'fhpage_page', 'type' => MENU_CALLBACK, 'access' => TRUE);
  }
  return $items;
}

/**
 * Menu callback
 */
function fhpage_page($type = NULL) {
	if($params = variable_get("fhpage_type_$type", '')) {
		$output = '';
		drupal_set_title($params['title']);
    if($params['header']) {
      $output .="<div class=\"page-header\">".$params['header']."</div>\n";
    }
    $query = db_rewrite_sql("SELECT n.nid, n.sticky, n.created FROM {node} n WHERE n.type = '%s' AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC");
    if($pager = $params['pager']) {
      $result = pager_query($query, $pager, 0, NULL, $type);
    } else {
    	$result = db_query($query, $type);
    }
    if (db_num_rows($result)) {
      while ($node = db_fetch_object($result)) {
        $output .= node_view(node_load($node->nid), 1);
      }
      $pager ? $output .= theme('pager', NULL, $pager) : NULL;
    }
    return $output;		
	}
}

function _fhpage_page_list() {
	return array(
	  'partners' => t('Partners'),
    'campaign' => t('Campaigns')
  );
}