<?php
// $Id: location.ws.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Samoa

function location_province_list_ws() {
  return array('AN' => "A'ana",
    'AI' => "Aiga-i-le-Tai",
    'AT' => "Atua",
    'FA' => "Fa'asaleleaga",
    'GE' => "Gaga'emauga",
    'GF' => "Gagaifomauga",
    'PA' => "Palauli",
    'SA' => "Satupa'itea",
    'TU' => "Tuamasaga",
    'VF' => "Va'a-o-Fonoti",
    'VS' => "Vaisigano");
}

?>