<?php
// $Id: location.sr.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Suriname

function location_province_list_sr() {
  return array('BR' => "Brokopondo",
    'CM' => "Commewijne",
    'CR' => "Coronie",
    'MA' => "Marowijne",
    'NI' => "Nickerie",
    'PA' => "Para",
    'PM' => "Paramaribo",
    'SA' => "Saramacca",
    'SI' => "Sipaliwini",
    'WA' => "Wanica");
}

?>