<?php
// $Id: location.sv.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// El Salvador

function location_province_list_sv() {
  return array('AH' => "Ahuachapan",
    'CA' => "Cabanas",
    'CH' => "Chalatenango",
    'CU' => "Cuscatlan",
    'LB' => "La Libertad",
    'PZ' => "La Paz",
    'UN' => "La Union",
    'MO' => "Morazan",
    'SM' => "San Miguel",
    'SS' => "San Salvador",
    'SA' => "Santa Ana",
    'SV' => "San Vicente",
    'SO' => "Sonsonate",
    'US' => "Usulutan");
}

?>