<?php
// $Id: location.sw.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Sweden

function location_province_list_sw() {
  return array('ST' => "Stockholm",
    'UP' => "Uppdala",
    'SO' => "Sodermanland",
    'OG' => "Ostergotland",
    'JO' => "Jonkping",
    'KR' => "Kronoberg",
    'KA' => "Kalmar",
    'GO' => "Gotland",
    'BL' => "Blekinge",
    'SK' => "Skane",
    'HA' => "Halland",
    'VG' => "Vastra Gotaland",
    'VL' => "Varmland",
    'OR' => "Orebro",
    'VM' => "Vastmanland",
    'DA' => "Dalama",
    'GA' => "Gavleborg",
    'VN' => "Vasternorrland",
    'JA' => "Jamtland",
    'VB' => "Vasterbotten",
    'NO' => "Norrbotten");
}

?>