<?php
// $Id: location.sn.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Senegal

function location_province_list_sn() {
  return array('DA' => "Dakar",
    'DI' => "Diourbel",
    'FA' => "Fatick",
    'KA' => "Kaolack",
    'KO' => "Kolda",
    'LO' => "Louga",
    'MA' => "Matam",
    'SL' => "Saint-Louis",
    'TA' => "Tambacounda",
    'TH' => "Thies ",
    'ZI' => "Ziguinchor");
}

?>