<?php
// $Id: location.mz.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Mozambique

function location_province_list_mz() {
  return array('CD' => "Cabo Delgado",
    'GZ' => "Gaza",
    'IN' => "Inhambane",
    'MN' => "Manica",
    'MC' => "Maputo (city)",
    'MP' => "Maputo",
    'NA' => "Nampula",
    'NI' => "Niassa",
    'SO' => "Sofala",
    'TE' => "Tete",
    'ZA' => "Zambezia");
}

?>