<?php
// $Id: location.qa.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Qatar

function location_province_list_qa() {
  return array('DW' => "Ad Dawhah",
    'GW' => "Al Ghuwayriyah",
    'JM' => "Al Jumayliyah",
    'KR' => "Al Khawr",
    'WK' => "Al Wakrah",
    'RN' => "Ar Rayyan",
    'JB' => "Jarayan al Batinah",
    'MS' => "Madinat ash Shamal",
    'UD' => "Umm Sa'id",
    'UL' => "Umm Salal");
}

?>