<?php
// $Id: location.md.inc,v 1.1.2.1 2006/03/08 06:53:16 dww Exp $

// Moldova, Republic of

function location_province_list_md() {
  return array('GA' => "Gagauzia",
    'CU' => "Chisinau",
    'BA' => "Balti",
    'CA' => "Cahul",
    'ED' => "Edinet",
    'LA' => "Lapusna",
    'OR' => "Orhei",
    'SO' => "Soroca",
    'TI' => "Tighina",
    'UN' => "Ungheni",
    'SN' => "Stânga Nistrului");
}

?>