-- Now there are options for same country
ALTER TABLE `fh_country_shipping` DROP PRIMARY KEY,
 ADD PRIMARY KEY(`countrycode`, `company`);

INSERT INTO `fh_country_shipping` VALUES('af', 'Afghanistan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('al', 'Albania', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('dz', 'Algeria', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('as', 'American Samoa', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ad', 'Andorra', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('ao', 'Angola', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ai', 'Anguilla', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ag', 'Antigua and Barbuda', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ar', 'Argentina', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('am', 'Armenia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('aw', 'Aruba', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('au', 'Australia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('at', 'Austria', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('az', 'Azerbaijan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bs', 'Bahamas', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bh', 'Bahrain', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bd', 'Bangladesh', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bb', 'Barbados', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('by', 'Belarus', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('be', 'Belgium', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('bz', 'Belize', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bj', 'Benin', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bm', 'Bermuda', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bt', 'Bhutan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bo', 'Bolivia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ba', 'Bosnia and Herzegovina', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('bw', 'Botswana', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('br', 'Brazil', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('vg', 'British Virgin Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bn', 'Brunei Darussalam', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bg', 'Bulgaria', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('bf', 'Burkina Faso', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('bi', 'Burundi', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kh', 'Cambodia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cm', 'Cameroon', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ca', 'Canada', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cv', 'Cape Verde', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ky', 'Cayman Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cf', 'Central African Republic', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('td', 'Chad (Tchad)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cl', 'Chile', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cn', 'China', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('co', 'Colombia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('km', 'Comoros', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cg', 'Congo (Republic of the Congo)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ck', 'Cook Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cr', 'Costa Rica', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ci', 'Cote d\'Ivoire (Ivory Coast)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('hr', 'Croatia (Hrvatska)', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('cu', 'Cuba', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cy', 'Cyprus', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('cz', 'Czech Republic', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('cd', 'Democratic Republic of the Congo (formerly Zaire)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('dk', 'Denmark', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('dj', 'Djibouti', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('dm', 'Dominica', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('do', 'Dominican Republic', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ec', 'Ecuador', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('eg', 'Egypt', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sv', 'El Salvador', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gq', 'Equatorial Guinea', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('er', 'Eritrea', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ee', 'Estonia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('et', 'Ethiopia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('fk', 'Falkland Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('fo', 'Faroe Islands', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('fm', 'Federated States of Micronesia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('fj', 'Fiji', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('fi', 'Finland', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('mk', 'Former Yugoslav Republic of Macedonia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('fr', 'France', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('gf', 'French Guiana', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pf', 'French Polynesia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ga', 'Gabon', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gm', 'Gambia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ge', 'Georgia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('de', 'Germany (Deutschland)', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('gh', 'Ghana', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gi', 'Gibraltar', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('gr', 'Greece', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('gl', 'Greenland', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('gd', 'Grenada', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gp', 'Guadeloupe', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gu', 'Guam', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gt', 'Guatemala', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gn', 'Guinea', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gw', 'Guinea-Bissau', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('gy', 'Guyana', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ht', 'Haiti', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('hn', 'Honduras', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('hk', 'Hong Kong', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('hu', 'Hungary', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('is', 'Iceland', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('in', 'India', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('id', 'Indonesia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ir', 'Iran', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ie', 'Ireland', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('il', 'Israel', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('jm', 'Jamaica', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('jp', 'Japan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('jo', 'Jordan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kz', 'Kazakhstan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ke', 'Kenya', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ki', 'Kiribati', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kw', 'Kuwait', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kg', 'Kyrgyzstan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('la', 'Laos', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('lv', 'Latvia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('lb', 'Lebanon', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ls', 'Lesotho', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('lr', 'Liberia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ly', 'Libya', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('li', 'Liechtenstein', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('lt', 'Lithuania', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('lu', 'Luxembourg', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('mo', 'Macao (Macau)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mg', 'Madagascar', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mw', 'Malawi', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('my', 'Malaysia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mv', 'Maldives', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ml', 'Mali', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mt', 'Malta', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('mh', 'Marshall Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mq', 'Martinique', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mr', 'Mauritania', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mu', 'Mauritius', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mx', 'Mexico', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('md', 'Moldova', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('mc', 'Monaco', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('mn', 'Mongolia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ms', 'Montserrat', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ma', 'Morocco', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mz', 'Mozambique', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mm', 'Myanmar (Burma)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('na', 'Namibia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('nr', 'Nauru', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('np', 'Nepal', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('nl', 'Netherlands', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('nc', 'New Caledonia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('nz', 'New Zealand', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ni', 'Nicaragua', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ne', 'Niger', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ng', 'Nigeria', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('nu', 'Niue', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('mp', 'Northern Mariana Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('no', 'Norway', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('om', 'Oman', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pk', 'Pakistan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pw', 'Palau', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ps', 'Palestinian Territories (West Bank and Gaza Strip)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pa', 'Panama', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pg', 'Papua New Guinea', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('py', 'Paraguay', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pe', 'Peru', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ph', 'Philippines', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('pl', 'Poland', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('pt', 'Portugal', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('pr', 'Puerto Rico', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('qa', 'Qatar', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('re', 'Reunion', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ro', 'Romania', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('ru', 'Russia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('rw', 'Rwanda', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kn', 'Saint Kitts and Nevis', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('lc', 'Saint Lucia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('vc', 'Saint Vincent and the Grenadines', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ws', 'Samoa', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sa', 'Saudi Arabia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sn', 'Senegal', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('cs', 'Serbia and Montenegro', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('sc', 'Seychelles', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sl', 'Sierra Leone', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sg', 'Singapore', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sk', 'Slovakia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('si', 'Slovenia', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('so', 'Somalia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('za', 'South Africa', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('kr', 'South Korea', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('es', 'Spain (Espana)', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('lk', 'Sri Lanka', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sd', 'Sudan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sr', 'Suriname', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('sz', 'Swaziland', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('se', 'Sweden', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('sw', 'Sweden', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('ch', 'Switzerland (Confoederatio Helvetica)', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('sy', 'Syria', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tw', 'Taiwan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tj', 'Tajikistan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tz', 'Tanzania', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('th', 'Thailand', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tl', 'Timor-Leste (East Timor)', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tg', 'Togo', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('to', 'Tonga', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tt', 'Trinidad and Tobago', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tn', 'Tunisia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tr', 'Turkey', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tm', 'Turkmenistan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tc', 'Turks and Caicos Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('tv', 'Tuvalu', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('vi', 'U.S. Virgin Islands', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ug', 'Uganda', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ua', 'Ukraine', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('ae', 'United Arab Emirates', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('uk', 'United Kingdom', 'EasyMail', 'EM_eu');
INSERT INTO `fh_country_shipping` VALUES('us', 'United States', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('uy', 'Uruguay', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('uz', 'Uzbekistan', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('vu', 'Vanuatu', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ve', 'Venezuela', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('vn', 'Vietnam', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('ye', 'Yemen', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('zm', 'Zambia', 'EasyMail', 'EM_world');
INSERT INTO `fh_country_shipping` VALUES('zw', 'Zimbabwe', 'EasyMail', 'EM_world');


INSERT INTO `fh_shipping_price` VALUES('0.02', 'EasyMail', 'EM_eu', '3.3');
INSERT INTO `fh_shipping_price` VALUES('0.05', 'EasyMail', 'EM_eu', '3.9');
INSERT INTO `fh_shipping_price` VALUES('0.1', 'EasyMail', 'EM_eu', '4.2');
INSERT INTO `fh_shipping_price` VALUES('0.25', 'EasyMail', 'EM_eu', '5');
INSERT INTO `fh_shipping_price` VALUES('0.35', 'EasyMail', 'EM_eu', '5.7');
INSERT INTO `fh_shipping_price` VALUES('0.5', 'EasyMail', 'EM_eu', '7');
INSERT INTO `fh_shipping_price` VALUES('1', 'EasyMail', 'EM_eu', '8.2');
INSERT INTO `fh_shipping_price` VALUES('1.5', 'EasyMail', 'EM_eu', '10.6');
INSERT INTO `fh_shipping_price` VALUES('2', 'EasyMail', 'EM_eu', '11.7');
INSERT INTO `fh_shipping_price` VALUES('0.02', 'EasyMail', 'EM_world', '3.4');
INSERT INTO `fh_shipping_price` VALUES('0.05', 'EasyMail', 'EM_world', '4');
INSERT INTO `fh_shipping_price` VALUES('0.1', 'EasyMail', 'EM_world', '4.3');
INSERT INTO `fh_shipping_price` VALUES('0.25', 'EasyMail', 'EM_world', '5.5');
INSERT INTO `fh_shipping_price` VALUES('0.35', 'EasyMail', 'EM_world', '7.4');
INSERT INTO `fh_shipping_price` VALUES('0.5', 'EasyMail', 'EM_world', '9');
INSERT INTO `fh_shipping_price` VALUES('1', 'EasyMail', 'EM_world', '11.2');
INSERT INTO `fh_shipping_price` VALUES('1.5', 'EasyMail', 'EM_world', '16.7');
INSERT INTO `fh_shipping_price` VALUES('2', 'EasyMail', 'EM_world', '19.2');
