<?php
// $Id: generic.module,v 1.4 2005/03/01 03:13:50 mathias Exp $

/********************************************************************
 * Drupal Hooks
 ********************************************************************/

function generic_help($section = 'admin/help#generic') {
  switch ($section) {
    case 'admin/modules#description':
      return t('Creates a generic product. Dependency: product.module');
  }
}

function generic_productapi(&$node, $op, $a3 = null, $a4 = null) {
  switch ($op) {
    case 'wizard_select':
      return array('generic' => t('non-shippable product'));

    case 'is_shippable':
      return false;
      
    case 'in_stock':
      return true;
  }
}

?>
